package mmm;

/**
 * This class provides the properties that are needed to be loaded from
 * language-dependent XML files.
 * 
 * @author Richard McKenna
 * @author ?
 * @version 1.0
 */
public enum mmmLanguageProperty {
//    SELECTION_TOOL_ICON,
//    SELECTION_TOOL_TOOLTIP,
    
    REMOVE_ICON,
    REMOVESTATION_TOOLTIP,
    REMOVELINE_TOOLTIP,
    
    ADD_ICON,
    ADDSTATIONTOLINE_TOOLTIP,
    REMOVESTATIONFROMLINE_TOOLTIP,
    ADDLINE_TOOLTIP,
    ADDSTATION_TOOLTIP,
    LISTSTATIONS_ICON,
    LISTSTATIONS_TOOLTIP,
    
    SNAP_TOOLTIP,
    MOVELABEL_TOOLTIP,
    ROTATELABEL_ICON,
    ROTATELABEL_TOOLTIP,
    FINDROUTE_ICON,
    FINDROUTE_TOOLTIP,
    SETIBG_TOOLTIP,
    ADDIMAGE_TOOLTIP,
    ADDLABEL_TOOLTIP,
    REMOVEELEMENT_TOOLTIP,
    BOLD_ICON,
    BOLD_TOOLTIP,    
    ITALICS_ICON,
    ITALICS_TOOLTIP,
    ZOOMIN_ICON,
    ZOOMIN_TOOLTIP,
    ZOOMOUT_ICON,
    ZOOMOUT_TOOLTIP,
    ENLARGE_ICON,
    ENLARGE_TOOLTIP,
    COMPRESS_ICON,
    COMPRESS_TOOLTIP,
//    ELLIPSE_ICON,
//    ELLIPSE_TOOLTIP,
//    
//    IMAGE_ICON,
//    IMAGE_TOOLTIP,
    
    TEXT_ICON,
    TEXT_TOOLTIP,
    

    
    MOVE_TO_BACK_ICON,
    MOVE_TO_BACK_TOOLTIP,
    MOVE_TO_FRONT_ICON,
    MOVE_TO_FRONT_TOOLTIP,
    
    BACKGROUND_TOOLTIP,
    FILL_TOOLTIP,
    OUTLINE_TOOLTIP,
    
    SNAPSHOT_ICON,
    SNAPSHOT_TOOLTIP,
}